apiVersion: v1
kind: Pod
metadata:
  name: api-pod
spec:
  containers:
    - image: jeremyarden/sc-server:latest
      name: node-api
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapi
  labels:
    run: nodeapi
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: nodeapi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodeapi
  name: nodeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodeapi
    spec:
      containers:
      - image: jeremyarden/sc-server:latest
        name: node-api
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 3000 
status: {}