apiVersion: v1
kind: Pod
metadata:
  name: user-pod
spec:
  containers:
    - image: jeremyarden/sc-user:latest
      name: user-api
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: userapi
  labels:
    run: userapi
spec:
  ports:
  - port: 8088
    protocol: TCP
  selector:
    app: userapi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: userapi
  name: userapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: userapi
    spec:
      containers:
      - image: jeremyarden/sc-user:latest
        name: user-api
        imagePullPolicy: Always
        resources: {}
        env:
          - name: MONGO_URL
            value: mongo
        ports:
          - containerPort: 8088 
status: {}